apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-fastapi
  labels:
    name: python-fastapi
spec:
  replicas: 3
  selector:
    matchLabels:
      name: python-fastapi
  template:
    metadata:
      labels:
        name: python-fastapi
    spec:
      containers:
        - name: python-fastapi
          image: btougeiro/python-fastapi:v1.0.0
          ports:
            - name: container-port
              containerPort: 8000
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
