apiVersion: v1
kind: Service
metadata:
  name: python-fastapi
spec:
  selector:
    name: python-fastapi
  ports:
    - name: python-fastapi
      protocol: TCP
      port: 80
      targetPort: container-port
